esphome:
  name: ${devicename}
  friendly_name: ${friendly}
  includes:
    - esp32-2432S028/components/hd_device_cyd/lv_conf.h
  libraries:
    - SPI
    - Wire
    - XPT2046_Touchscreen=https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4

esp32:
  board: esp32dev
  framework:
    type: arduino
