substitutions:
  device_name: cb3s-temp-and-hum
  friendly_name: CB3S Temperature and Humidity

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

bk72xx:
  board: cb3s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Fallback ${device_name}
    password: !secret wifi_ap_password

captive_portal:

ota:
  - platform: esphome
    password: !secret esphome_ota_password

button:
  - platform: restart
    name: "Restart"

# Tuya MCU on UART1 (BK72xx example)
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600
tuya:

# sensor:
#     # Uptime sensor
#   - platform: uptime
#     id: sys_uptime
#     type: seconds
#     name: Uptime Sensor    
#     entity_category: "diagnostic"
#   - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
#     name: "WiFi Signal dB"
#     id: wifi_signal_db
#     update_interval: 60s
#     entity_category: "diagnostic"

#   - platform: copy # Reports the WiFi signal strength in %
#     source_id: wifi_signal_db
#     name: "WiFi Signal Percent"
#     filters:
#       - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
#     unit_of_measurement: "%"
#     entity_category: "diagnostic"
#     device_class: ""

#   # Internal Temperature Sensor
#   - platform: internal_temperature
#     id: esp_internal_temperature
#     name: "Internal Temperature"
#     entity_category: "diagnostic"

#   # Free memory
#   - platform: template
#     id: esp_memory
#     icon: mdi:memory
#     name: Free Memory
#     lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
#     unit_of_measurement: 'kB'
#     state_class: measurement
#     entity_category: "diagnostic"

# text_sensor:
#     - platform: wifi_info
#       ip_address:
#         name: IP Address
#       mac_address:
#         name: Mac Wifi Address
