substitutions:
  devicename: esp32c3-mini-va
  friendly: Esp32 VA Meter

esphome:
  name: ${devicename}
  friendly_name: ${friendly}
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: WARN
  logs:
    sensor: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 15min

web_server:
  port: 80
  version: 3
  include_internal: true
  ota: false
  sorting_groups:
    - id: measurements
      name: "Measurements"
      sorting_weight: 10
    - id: peak_values
      name: "Peak Values"
      sorting_weight: 20
    - id: consumption
      name: "Power Consumption"
      sorting_weight: 30
    - id: diagnostic
      name: "Diagnostic"
      sorting_weight: 100  

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  id: wifi_parent
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  reboot_timeout: 15min
  power_save_mode: NONE
  output_power: 20dB

  ap:
    ssid: ${devicename}
    password: "01234567890"

captive_portal:

i2c:
  sda: GPIO01
  scl: GPIO02
  scan: false
  id: bus_i2c

status_led:
  pin:
    number: GPIO8
    inverted: true

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Kyiv
    update_interval: 30min

spi:
  clk_pin: GPIO04
  mosi_pin: GPIO07

output:
  - platform: ledc
    pin: GPIO10
    id: lcd_backlight

light:
  - platform: monochromatic
    output: lcd_backlight
    name: "LCD Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0s
    on_turn_on:
      - light.control:
          id: backlight
          brightness: 50%

display:
  - platform: ili9xxx
#  - platform: st7735
    id: tft_display
    model: ST7735
    invert_colors: false
    show_test_card: false
    dimensions:
      height: 160
      width: 128
    cs_pin: GPIO05
    dc_pin: GPIO06
    reset_pin: GPIO00
    rotation: 270

font:
  - file: "gfonts://Montserrat"
    id: font_large
    size: 26
  - file: "gfonts://Montserrat"
    id: font_medium
    size: 14
  - file: "gfonts://Montserrat"
    id: font_small
    size: 10

lvgl:
  log_level: WARN
  displays:
    - tft_display

  style_definitions:
    - id: style_screen
      bg_color: 0x000000
      text_color: 0xFFFFFF
    - id: style_voltage
      text_color: 0x00FF00 # Green
      text_font: font_large
      pad_all: 0
    - id: style_current
      text_color: 0xFFFF00 # Yellow
      text_font: font_large
      pad_all: 0
    - id: style_power
      text_color: 0xFF0000 # Red
      text_font: font_large
      pad_all: 0

    - id: style_box
      border_width: 1
      border_color: 0x4444FF
      radius: 0
      bg_color: 0x000000
      text_color: 0xFFFFFF
      text_font: font_small
      pad_all: 0
      scrollbar_mode: "OFF"

    - id: style_box_top
      border_width: 0
      radius: 0
      bg_color: 0x000000
      text_color: 0xFFFFFF
      text_font: font_small
      pad_all: 0
      scrollbar_mode: "OFF"

    - id: style_box_bottom
      border_width: 0
      radius: 0
      bg_color: 0x000000
      text_color: 0xFFFFFF
      text_font: font_small
      pad_all: 0
      scrollbar_mode: "OFF"

    - id: style_unit_box
      border_width: 1
      border_color: 0xFFFFFF # White
      radius: 0
      bg_color: 0x000000
      text_color: 0xFFFFFF
      text_font: font_small
      pad_all: 0
      scrollbar_mode: "OFF"

    - id: style_unit_label_v
      text_color: 0x00FF00
      text_font: font_medium
      pad_all: 0
    - id: style_unit_label_a
      text_color: 0xFFFF00
      text_font: font_medium
      pad_all: 0
    - id: style_unit_label_w
      text_color: 0xFF0000
      text_font: font_medium
      pad_all: 0

    - id: style_peak_label
      text_color: 0xAAAAAA # Dimmer white for headers
      text_font: font_small
      text_align: LEFT
      pad_all: 0

    - id: style_peak_val
      text_color: 0xADD8E6 # Light Blue for values
      text_font: font_small
      pad_all: 0

    - id: style_bottom_label
      text_font: font_small
      pad_all: 0

    - id: style_consumption_box
      border_width: 0
      radius: 0
      bg_color: 0x000000
      text_color: 0xFFFFFF
      text_font: font_small
      pad_all: 0
      scrollbar_mode: "OFF"
    - id: style_border_line
      bg_color: 0x4444FF
      radius: 0

  pages:
    - id: main_page
      styles: style_screen
      widgets:
        # LEFT PANEL - TOP (WiFi & IP)
        - obj:
            x: 0
            y: 0
            width: 107
            height: 20
            styles: style_box_top
            widgets:
              - obj: # Bottom Border
                  x: 0
                  y: 19
                  width: 107
                  height: 1
                  styles: style_border_line
              - obj: # Right Border
                  x: 106
                  y: 0
                  width: 1
                  height: 20
                  styles: style_border_line
              - obj: # WiFi Icon Container
                  x: 4
                  y: 3
                  width: 20
                  height: 14
                  bg_opa: 0
                  border_width: 0
                  pad_all: 0
                  widgets:
                    - obj: { id: wifi_bar_1, x: 0, y: 10, width: 3, height: 4, bg_color: 0x444444, radius: 0, border_width: 0 }
                    - obj: { id: wifi_bar_2, x: 5, y: 7, width: 3, height: 7, bg_color: 0x444444, radius: 0, border_width: 0 }
                    - obj: { id: wifi_bar_3, x: 10, y: 4, width: 3, height: 10, bg_color: 0x444444, radius: 0, border_width: 0 }
                    - obj: { id: wifi_bar_4, x: 15, y: 1, width: 3, height: 13, bg_color: 0x444444, radius: 0, border_width: 0 }
              - label: { id: ip_label, text: "---", x: 28, y: 3, styles: style_bottom_label }

        # LEFT PANEL - MIDDLE (V, A, P)
        - obj: # Voltage Unit Box
            x: 0
            y: 20
            width: 20
            height: 29
            styles: style_unit_box
            widgets:
              - label: { text: "V", align: CENTER, styles: style_unit_label_v }
        - label:
            id: voltage_value
            styles: style_voltage
            x: 24
            y: 19
            text: "00.000"
        
        - obj: # Current Unit Box
            x: 0
            y: 49
            width: 20
            height: 30
            styles: style_unit_box
            widgets:
              - label: { text: "A", align: CENTER, styles: style_unit_label_a }
        - label:
            id: current_value
            styles: style_current
            x: 24
            y: 48
            text: "00.000"

        - obj: # Power Unit Box
            x: 0
            y: 79
            width: 20
            height: 29
            styles: style_unit_box
            widgets:
              - label: { text: "W", align: CENTER, styles: style_unit_label_w }
        - label:
            id: power_value
            styles: style_power
            x: 24
            y: 78
            text: "000.000"

        # LEFT PANEL - BOTTOM (Energy & Charge)
        - obj:
            x: 0
            y: 108
            width: 107
            height: 20
            styles: style_box_bottom
            widgets:
              - obj: # Top Border
                  x: 0
                  y: 0
                  width: 107
                  height: 1
                  styles: style_border_line
              - obj: # Right Border
                  x: 106
                  y: 0
                  width: 1
                  height: 20
                  styles: style_border_line
              - label:
                  id: energy_value
                  x: 4
                  y: 3
                  styles: style_peak_val
                  text: "0.000k"
              - label:
                  id: charge_value
                  align: TOP_RIGHT
                  x: -2
                  y: 3
                  styles: style_peak_val
                  text: "0.000A"

        # RIGHT PANEL - 4 Sections (Peak VAP + Load Time)
        - obj: # Box 1: Peak Voltage
            width: 53
            height: 32
            x: 107
            y: 0
            styles: style_box
            widgets:
              - label: { text: "P-V", x: 2, y: 1, styles: style_peak_label }
              - label: { id: peak_v_label, x: 2, y: 12, styles: style_peak_val, text: "00.000V" }
        - obj: # Box 2: Peak Current
            width: 53
            height: 32
            x: 107
            y: 32
            styles: style_box
            widgets:
              - label: { text: "P-I", x: 2, y: 1, styles: style_peak_label }
              - label: { id: peak_a_label, x: 2, y: 12, styles: style_peak_val, text: "0.000A" }
        - obj: # Box 3: Peak Power
            width: 53
            height: 32
            x: 107
            y: 64
            styles: style_box
            widgets:
              - label: { text: "P-W", x: 2, y: 1, styles: style_peak_label }
              - label: { id: peak_w_label, x: 2, y: 12, styles: style_peak_val, text: "0.000W" }
        - obj: # Box 4: Load Time
            width: 53
            height: 32
            x: 107
            y: 96
            styles: style_box
            widgets:
              - label: { text: "TIME", x: 2, y: 1, styles: style_peak_label }
              - label: { id: active_time_label, x: 2, y: 12, styles: style_bottom_label, text: "00:00" }

interval:
  - interval: 100ms
    then:
      - lvgl.label.update:
          id: voltage_value
          text: !lambda |-
            float v = id(bus_voltage).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3f" : "%.2f", v);
            return buf;
      - lvgl.label.update:
          id: current_value
          text: !lambda |-
            float v = id(current).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3f" : "%.2f", v);
            return buf;
      - lvgl.label.update:
          id: power_value
          text: !lambda |-
            float v = id(power).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3f" : "%.2f", v);
            return buf;
      - lvgl.label.update:
          id: peak_v_label
          text: !lambda |-
            float v = id(peak_voltage).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3fV" : "%.2fV", v);
            return buf;
      - lvgl.label.update:
          id: peak_a_label
          text: !lambda |-
            float v = id(peak_current).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3fA" : "%.2fA", v);
            return buf;
      - lvgl.label.update:
          id: peak_w_label
          text: !lambda |-
            float v = id(peak_power).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3fW" : "%.2fW", v);
            return buf;
      - lvgl.obj.update:
          id: main_page
      - lambda: |-
          uint32_t c_off = 0x444444;
          uint32_t c_on = 0xFFFFFF;
          uint32_t b1 = c_off, b2 = c_off, b3 = c_off, b4 = c_off;
          if (id(wifi_signal_db).has_state()) {
            float rssi = id(wifi_signal_db).state;
            if (rssi > -90) b1 = c_on;
            if (rssi > -80) b2 = c_on;
            if (rssi > -70) b3 = c_on;
            if (rssi > -60) b4 = c_on;
          }
          lv_obj_set_style_bg_color(id(wifi_bar_1), lv_color_hex(b1), LV_PART_MAIN);
          lv_obj_set_style_bg_color(id(wifi_bar_2), lv_color_hex(b2), LV_PART_MAIN);
          lv_obj_set_style_bg_color(id(wifi_bar_3), lv_color_hex(b3), LV_PART_MAIN);
          lv_obj_set_style_bg_color(id(wifi_bar_4), lv_color_hex(b4), LV_PART_MAIN);
      - lvgl.label.update:
          id: ip_label
          text: !lambda |-
            if (id(wifi_signal_db).has_state()) {
              return id(wifi_parent).get_ip_addresses()[0].str().c_str();
            }
            return "---";
      - lvgl.label.update:
          id: active_time_label
          text: !lambda |-
            int total_seconds = (int)id(load_active_time).state;
            int minutes = (total_seconds % 3600) / 60;
            int seconds = total_seconds % 60;
            char buf[10];
            sprintf(buf, "%02d:%02d", minutes, seconds);
            return buf;
      - lvgl.label.update:
          id: energy_value
          text: !lambda |-
            float v = id(energy_consumption).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3fkWh" : "%.2fkWh", v);
            return buf;
      - lvgl.label.update:
          id: charge_value
          text: !lambda |-
            float v = id(charge_consumption).state;
            char buf[16];
            sprintf(buf, (v < 10.0f) ? "%.3fAh" : "%.2fAh", v);
            return buf;

sensor:
  # System sensors
  - platform: uptime
    id: sys_uptime
    name: "Uptime"
    entity_category: diagnostic
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostic
      sorting_weight: 10

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
    web_server:
      sorting_group_id: diagnostic
      sorting_weight: 20

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""
    accuracy_decimals: 0
    web_server:
      sorting_group_id: diagnostic
      sorting_weight: 30

  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
    entity_category: diagnostic
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostic
      sorting_weight: 40

  - platform: template
    id: esp_memory
    name: "Free Memory"
    icon: mdi:memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: diagnostic
    update_interval: 60s
    accuracy_decimals: 0
    web_server:
      sorting_group_id: diagnostic
      sorting_weight: 50

  # INA226 Power Monitor Sensors
  - platform: ina226
    i2c_id: bus_i2c
    address: 0x40
    shunt_resistance: 0.002 ohm
    max_current: 20 A
    adc_time: 1100us
    adc_averaging: 16
    update_interval: 100ms

    bus_voltage:
      name: "Voltage"
      id: bus_voltage
      icon: mdi:flash
      accuracy_decimals: 3
      web_server:
        sorting_group_id: measurements
        sorting_weight: 10
      filters:
        - multiply: 0.9799  # Calibration factor: 14.66V / 14.96V
        - lambda: "return (abs(x) < 0.001) ? 0.0 : x;"
        - sliding_window_moving_average:
            window_size: 4
            send_every: 1

    shunt_voltage:
      name: "Shunt Voltage"
      id: shunt_voltage
      icon: mdi:flash-outline
      accuracy_decimals: 4
      internal: false
      web_server:
        sorting_group_id: measurements
        sorting_weight: 40

    current:
      name: "Current"
      id: current
      icon: mdi:current-dc
      accuracy_decimals: 3
      web_server:
        sorting_group_id: measurements
        sorting_weight: 20
      filters:
        - multiply: 0.545
        - lambda: "return (abs(x) < 0.001) ? 0.0 : x;"
        - sliding_window_moving_average:
            window_size: 4
            send_every: 1

    power:
      name: "Power"
      id: power
      icon: mdi:lightning-bolt
      accuracy_decimals: 3
      web_server:
        sorting_group_id: measurements
        sorting_weight: 30
      filters:
        - lambda: "return (abs(x) < 0.001) ? 0.0 : x;"
        - sliding_window_moving_average:
            window_size: 4
            send_every: 1

  # Peak values tracking - using globals for reset functionality
  - platform: template
    name: "Peak Voltage"
    id: peak_voltage
    icon: mdi:flash-triangle
    unit_of_measurement: "V"
    accuracy_decimals: 3
    web_server:
      sorting_group_id: peak_values
      sorting_weight: 10
    update_interval: 100ms
    lambda: |-
      float current_voltage = id(bus_voltage).state;
      if (current_voltage > id(peak_voltage).state || isnan(id(peak_voltage).state)) {
        return current_voltage;
      }
      return id(peak_voltage).state;

  - platform: template
    name: "Peak Current"
    id: peak_current
    icon: mdi:current-dc
    unit_of_measurement: "A"
    accuracy_decimals: 3
    web_server:
      sorting_group_id: peak_values
      sorting_weight: 20
    update_interval: 100ms
    lambda: |-
      float current_amp = id(current).state;
      if (current_amp > id(peak_current).state || isnan(id(peak_current).state)) {
        return current_amp;
      }
      return id(peak_current).state;

  - platform: template
    name: "Peak Power"
    id: peak_power
    icon: mdi:lightning-bolt-circle
    unit_of_measurement: "W"
    accuracy_decimals: 3
    web_server:
      sorting_group_id: peak_values
      sorting_weight: 30
    update_interval: 100ms
    lambda: |-
      float current_power = id(power).state;
      if (current_power > id(peak_power).state || isnan(id(peak_power).state)) {
        return current_power;
      }
      return id(peak_power).state;

  # Power Consumption Sensors
  - platform: integration
    name: "Energy Consumption"
    id: energy_consumption
    sensor: power
    time_unit: h
    icon: mdi:lightning-bolt
    accuracy_decimals: 3
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    web_server:
      sorting_group_id: consumption
      sorting_weight: 10
    filters:
      - multiply: 0.001  # Convert Wh to kWh

  - platform: integration
    name: "Charge Consumption"
    id: charge_consumption
    sensor: current
    time_unit: h
    icon: mdi:current-dc
    accuracy_decimals: 3
    unit_of_measurement: 'Ah'
    state_class: total_increasing
    web_server:
      sorting_group_id: consumption
      sorting_weight: 20

  - platform: template
    name: "Load Active Time"
    id: load_active_time
    icon: mdi:timer-outline
    unit_of_measurement: "s"
    accuracy_decimals: 0
    update_interval: 1s
    web_server:
      sorting_group_id: consumption
      sorting_weight: 40
    lambda: |-
      static uint32_t active_seconds = 0;
      // Handle reset from button or other sources
      if (id(load_active_time).has_state() && id(load_active_time).state == 0.0f) {
        active_seconds = 0;
      }
      if (id(current).state > 0.01) { // Threshold for "active" load
        active_seconds++;
      }
      return (float)active_seconds;

button:
  - platform: template
    name: "Reset Peak Values"
    icon: mdi:restart
    web_server:
      sorting_group_id: peak_values
      sorting_weight: 40
    on_press:
      - lambda: |-
          id(peak_voltage).publish_state(id(bus_voltage).state);
          id(peak_current).publish_state(id(current).state);
          id(peak_power).publish_state(id(power).state);

  - platform: template
    name: "Reset Consumption"
    icon: mdi:restart
    web_server:
      sorting_group_id: consumption
      sorting_weight: 30
    on_press:
      - lambda: |-
          id(energy_consumption).publish_state(0.0);
          id(charge_consumption).publish_state(0.0);
          id(load_active_time).publish_state(0.0);
