substitutions:
  devicename: luatos-esp32-c3-va
  friendly: Luatos Esp32 C3 VA Meter

esphome:
  name: ${devicename}
  friendly_name: ${friendly}
  platformio_options:
    # flash_mode defaults to qio, but Air101/LuatOS requires dio mode
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: WARN
  logs:
    sensor: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 15min

web_server:
  port: 80
  version: 3
  include_internal: true
  ota: false  

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 15min
  power_save_mode: LIGHT

  ap:
    ssid: ${devicename}
    password: "01234567890"

captive_portal:

spi:
  clk_pin: GPIO02
  mosi_pin: GPIO03
  # miso_pin: GPIO10

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: false
  id: bus_i2c

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Kyiv
    update_interval: 30min

sensor:
  # System sensors
  - platform: uptime
    id: sys_uptime
    name: "Uptime"
    entity_category: diagnostic
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""
    accuracy_decimals: 0

  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
    entity_category: diagnostic
    update_interval: 60s

  - platform: template
    id: esp_memory
    name: "Free Memory"
    icon: mdi:memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: diagnostic
    update_interval: 60s
    accuracy_decimals: 0

  # INA226 Power Monitor Sensors
  - platform: ina226
    i2c_id: bus_i2c
    address: 0x40
    shunt_resistance: 0.002 ohm
    max_current: 20 A
    adc_time: 1100us
    adc_averaging: 128
    update_interval: 1s

    bus_voltage:
      name: "Bus Voltage"
      id: bus_voltage
      icon: mdi:flash
      accuracy_decimals: 2
      filters:
        - multiply: 0.9799  # Calibration factor: 14.66V / 14.96V
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1

    shunt_voltage:
      name: "Shunt Voltage"
      id: shunt_voltage
      icon: mdi:flash-outline
      accuracy_decimals: 4
      internal: true

    current:
      name: "Current"
      id: current
      icon: mdi:current-dc
      accuracy_decimals: 3
      filters:
        - multiply: 0.545  # Calibration factor: 0.5A / 0.918A
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1

    power:
      name: "Power"
      id: power
      icon: mdi:lightning-bolt
      accuracy_decimals: 3
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1

  # Calculated Energy Sensors
  - platform: total_daily_energy
    name: "Daily Energy"
    id: daily_energy
    power_id: power
    icon: mdi:counter
    accuracy_decimals: 2
    filters:
      - multiply: 0.001  # Convert Wh to kWh
    unit_of_measurement: 'kWh'

  # Peak values tracking
  - platform: template
    name: "Peak Voltage"
    id: peak_voltage
    icon: mdi:flash-triangle
    unit_of_measurement: "V"
    accuracy_decimals: 2
    update_interval: 2s
    lambda: |-
      static float max_voltage = 0.0;
      float current_voltage = id(bus_voltage).state;
      if (current_voltage > max_voltage || isnan(max_voltage)) {
        max_voltage = current_voltage;
      }
      return max_voltage;

  - platform: template
    name: "Peak Current"
    id: peak_current
    icon: mdi:current-dc
    unit_of_measurement: "A"
    accuracy_decimals: 3
    update_interval: 2s
    lambda: |-
      static float max_current = 0.0;
      float current_amp = id(current).state;
      if (current_amp > max_current || isnan(max_current)) {
        max_current = current_amp;
      }
      return max_current;

  - platform: template
    name: "Peak Power"
    id: peak_power
    icon: mdi:lightning-bolt-circle
    unit_of_measurement: "W"
    accuracy_decimals: 3
    update_interval: 2s
    lambda: |-
      static float max_power = 0.0;
      float current_power = id(power).state;
      if (current_power > max_power || isnan(max_power)) {
        max_power = current_power;
      }
      return max_power;

button:
  - platform: template
    name: "Reset Peak Values"
    icon: mdi:restart
    on_press:
      - lambda: |-
          id(peak_voltage).publish_state(id(bus_voltage).state);
          id(peak_current).publish_state(id(current).state);
          id(peak_power).publish_state(id(power).state);
