substitutions:
  name: jc3248w535-sample
  friendly_name: JC3248W535 Display

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  libraries:
    - lvgl/lvgl@^9.2.0

esp32:
  board: esp32s3-devkit-c
  framework:
    type: arduino
  variant: ESP32S3
  flash_size: 16MB
  psram: "opi"
  board_build.flash_mode: qio
  board_build.psram_mode: opi

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret wifi_ap_password

# captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# Display configuration
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9488
    id: my_display
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4
    rotation: 0
    backlight_pin: GPIO27
    color_depth: RGB565
    dimensions:
      width: 480
      height: 320
    data_rate: 40MHz
    transform:
      mirror_x: false
      mirror_y: false
    lvgl_available: true
    update_interval: 16ms

# Touch configuration
touchscreen:
  - platform: ft6336
    id: ft6336_touch
    interrupt_pin: GPIO36
    reset_pin: GPIO25
    address: 0x38
    display: my_display

font:
  - file: "gfonts://Roboto@400"
    id: roboto
    size: 80

# Time component for clock display
time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source: github://esphome/esphome@dev
    components: [ lvgl ]
    refresh: 0s

lvgl:
  on_boot:
    then:
      lambda: |-
        auto screen = lv_scr_act();
        
        // Create a black background
        lv_obj_set_style_bg_color(screen, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        
        // Create label for time
        auto time_label = lv_label_create(screen);
        lv_obj_set_style_text_font(time_label, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(time_label, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(time_label, "00:00");
        lv_obj_center(time_label);
        
        // Update time every second
        lv_timer_create([](lv_timer_t * timer) {
          auto time = id(homeassistant_time).now();
          auto label = (lv_obj_t*)timer->user_data;
          char time_str[6];
          sprintf(time_str, "%02d:%02d", time.hour, time.minute);
          lv_label_set_text(label, time_str);
        }, 1000, time_label);
