binary_sensor:
  - id: bedroom_android_tv
    platform: homeassistant
    entity_id: media_player.bedroom_android_tv
    publish_initial_state: true
    on_state:
      - if:
          condition:
            binary_sensor.is_on: bedroom_android_tv
          then:
            - lvgl.widget.enable:
                - bedroom_tv_vol_up_widget
                - bedroom_tv_vol_down_widget
          else:
            - lvgl.widget.disable:
                - bedroom_tv_vol_up_widget
                - bedroom_tv_vol_down_widget
