binary_sensor:
  - id: living_room_tv
    platform: homeassistant
    entity_id: media_player.living_room_tv
    publish_initial_state: true
    on_state:
      - if:
          condition:
            binary_sensor.is_on: living_room_tv
          then:
            - lvgl.widget.enable:
                - living_room_tv_playpause_widget
                - living_room_tv_stop_widget
                - living_room_tv_vol_up_widget
                - living_room_tv_vol_down_widget
          else:
            - lvgl.widget.disable:
                - living_room_tv_playpause_widget
                - living_room_tv_stop_widget
                - living_room_tv_vol_up_widget
                - living_room_tv_vol_down_widget
